### ISSUE TITLE
How to run select.py?

### ISSUE THREAD

**Issue by MES-physics** [bigd4/PyNEP#11]
After installing PyNEP into a python environment via pip, and setting the PYTHONPATH, what further steps are need to access and run select.py? 
 I also did ```chmod +x select.py```.
 I also put the line ```!/usr/bin/env python3.9``` on top of the file.
  I put a copy of the file into the bin directory (actually 2 different ones).
Trying to run by ```select.py``` or ```./select.py```  returns:
bash: ./select.py: No such file or directory

I'd appreciate your help.

**Comment by bigd4** [comment]
Maybe you can firstly run `python -c "import pynep; print(pynep.__path__)"` to ensure the pynep has been installed. If it is, you can `cd example ` and run `python plot_select_structure.py` as shown in https://pynep.readthedocs.io/en/latest/auto_examples/plot_select_structure.html#sphx-glr-auto-examples-plot-select-structure-py

**Comment by MES-physics** [comment]
OK thanks, I found the understandable way for me to tun these scripts is to run them inside the python environment I set up for the program, and rename them from a .py to a .sh file, put my she/bang line on top, and it works.
