### ISSUE TITLE
Updata NEP-CPU

### ISSUE THREAD

**Issue by Jonsnow-willow** [bigd4/PyNEP#16]
Nep_cpu has been updated, could you please update to the latest version? Thanks!

**Comment by bigd4** [comment]
Done. 
I directly copy `nep.cpp` and `nep.h` in [nep_cpu](https://github.com/brucefan1983/NEP_CPU/tree/main/src) into the `src`,  this will output information twice when the potential is created, but should not affect usage.

**Comment by Jonsnow-willow** [comment]
Thanks!
